#!/bin/sh

# usage: convert_package_list $package_list $repository_name

. distro/opensuse/parameters

case $arch in
	x86_64)
		not_arch="i.86"
		;;
	i586)
		not_arch="x86_64"
		;;
esac

distro/centos/convert_package_list "$1" "$2" | egrep -v \
                                                    "\.$not_arch\.rpm\|"
